# Generated by Django 3.1.7 on 2021-02-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('tier', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('win', models.CharField(max_length=50)),
                ('lose', models.CharField(max_length=50)),
                ('win_ratio', models.CharField(max_length=50)),
                ('most1', models.CharField(max_length=50)),
                ('most2', models.CharField(max_length=50)),
                ('most3', models.CharField(max_length=50)),
                ('cha_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
